services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.     
    # Validator
    validator:
        class: Symfony\Component\Validator\Validator\ValidatorInterface
        public: true
        factory: 'validator.builder:getValidator'
    Symfony\Component\Validator\Validator\ValidatorInterface:
        alias: validator
    validator.builder:
        class: Symfony\Component\Validator\ValidatorBuilderInterface
        factory: ['Symfony\Component\Validator\Validation', createValidatorBuilder]
        calls:
            - [setConstraintValidatorFactory, ['@validator.validator_factory']]
            - [enableAnnotationMapping]            
    validator.mapping.class_metadata_factory:
        alias: validator
    validator.validator_factory:
        class: Symfony\Component\Validator\ContainerConstraintValidatorFactory
        arguments: ['@service_container'] 